### ISSUE TITLE
why doesnt the node have an option....

### ISSUE THREAD

**Issue by DrBlackross** [turtlecoin/turtlecoin-nodes-json#214]
why doesn't the node have an option to list itself or turtlecoin-ha (which i have yet to figure out)?
been running a node now for 5 months now, couldn't figure out why its not working like my LND node

**Comment by unternet** [comment]
This is not a productive use of the Github Issues section. Please submit a pull request with the functionality you'd like to see added, and it can be reviewed.

**Comment by brandonlehmann** [comment]
> why doesn't the node have an option to list itself or turtlecoin-ha (which i have yet to figure out)?
> been running a node now for 5 months now, couldn't figure out why its not working like my LND node

Because having the nodes report back in to a central authority that they exist automatically seems kind of sketch aeh? Listing a public node is optional and the process as it is **very** opt-in and requires that you show a basic understanding of how git and JSON work in the first place -- which isn't a bad entry barrier for asking for inclusion on the public list of nodes...

**Comment by DrBlackross** [comment]
yeah i got the sketch part, just being lazy
